appVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  backgroundTasks:
    scheduleExpiry: 6
  connectionPoolSetting:
    connectTimeOut: 15
    poolTimeOut: 10
    elswhereTimeOut: 11
    maxClientConnection: 8000
    maxKeepAliveConnection: 4000
    keepAliveExpiry: 12
    retryNumber: 2
    asyncDefaultTimeOut: 10
  activeCarriers:
    cma:  True
    hlag: False
    hmm: True
    iqax: True
    maersk: True
    msc: True
    one: True
    zim: True